@startuml usecase

left to right direction

actor User
actor Moderator
actor Admin

usecase "UC01. Login" as U1
usecase "UC02. Selecionar usuário" as U2
usecase "UC03. Criar página" as U3
usecase "UC04. Selecionar página" as U4
usecase "UC05. Seguir página" as U5

rectangle "UC06. Gerenciar página" as U6 {
    usecase "UC07. Banir usuário" as U7
    usecase "UC08. Renomear página" as U8
    usecase "UC09. Alterar imagem\nda página" as U9
    usecase "UC10. Alterar descrição\nda página" as U10
    usecase "UC11. Adicionar moderador" as U11
    usecase "UC12. Remover moderador" as U12
    usecase "UC13. Tornar moderador líder" as U13
    usecase "UC14. Arquivar página" as U14
    usecase "UC15. Deletar página" as U15
}

usecase "UC16. Criar postagem" as U16
usecase "UC17. Selecionar postagem" as U17
usecase "UC18. Curtir postagem" as U18

rectangle "UC19. Gerenciar postagem" as U19{
    usecase "UC20. Editar postagem" as U20
    usecase "UC21. Remover postagem" as U21
}

usecase "UC22. Criar comentário" as U22
usecase "UC23. Selecionar comentário" as U23
usecase "UC24. Curtir comentário" as U24

rectangle "U25. Gerenciar comentário" as U25 {
    usecase "UC26. Editar comentário" as U26
    usecase "UC27. Remover comentário" as U27
}

usecase "UC28. Avaliar um perfil" as U28

rectangle "UC29. Gerenciar usuário" as U29 {
    usecase "UC30. Desativar usuário" as U30
    usecase "UC31. Ativar usuário" as U31
}

usecase "UC32. Selecionar moderador" as U32

User --> U3
User --> U5
User --> U16
User --> U18
User --> U19
User --> U22
User --> U24
User --> U25
User --> U28

Admin --> U6
Admin --> U29

Moderator --> U6

U2 ..> U1 : <<inherits>>
U4 ..> U1 : <<inherits>>

U5 ..> U4 : <<inherits>>
U6 ..> U4 : <<inherits>>

U6 <.. U7 : <<extends>>
U6 <.. U8 : <<extends>>
U6 <.. U9 : <<extends>>
U6 <.. U10 : <<extends>>
U6 <.. U11 : <<extends>>
U6 <.. U12 : <<extends>>
U6 <.. U13 : <<extends>>
U6 <.. U14 : <<extends>>
U6 <.. U15 : <<extends>>
U6 <.. U19 : <<extends>>
U6 <.. U25 : " " "<<extends>>"

U7 ..> U2 : <<inherits>>
U11 ..> U2 : <<inherits>>
U12 ..> U32 : <<inherits>>
U13 ..> U32 : <<inherits>>

U17 ..> U4 : <<inherits>>

U18 ..> U17 : <<inherits>>
U19 ..> U17 : <<inherits>>

U19 <.. U20 : <<extends>>
U19 <.. U21 : <<extends>>

U22 ..> U17 : <<inherits>>

U23 ..> U17 : <<inherits>>

U24 ..> U23 : <<inherits>>
U25 ..> U23 : <<inherits>>

U25 <.. U26 : <<extends>>
U25 <.. U27 : <<extends>>

U28 ..> U2 : <<inherits>>

U29 ..> U2 : <<inherits>>
U29 <.. U30 : <<extends>>
U29 <.. U31 : <<extends>>

@enduml